# Generated by Django 2.2.12 on 2021-01-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('country_code', models.CharField(max_length=2)),
                ('current_balance', models.CharField(max_length=10)),
                ('interest_rate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=42)),
                ('deposit_date', models.CharField(max_length=10)),
                ('deposit_currency', models.CharField(max_length=3)),
                ('new_balance', models.CharField(max_length=20)),
            ],
        ),
    ]
