# Generated by Django 2.2.12 on 2021-01-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit_amount',
            field=models.CharField(default='0.00', max_length=10),
        ),
    ]
