# Generated by Django 2.2.12 on 2021-02-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210202_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default='NEED TO FORMAT EMAIL', max_length=42),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='None', max_length=42),
        ),
        migrations.AddField(
            model_name='account',
            name='profits',
            field=models.CharField(default='0.00', max_length=42),
        ),
        migrations.AlterField(
            model_name='account',
            name='country_code',
            field=models.CharField(default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.CharField(default='0.00', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='interest_rate',
            field=models.CharField(default='0.01', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deposit_date',
            field=models.CharField(default='NEED TO FORMAT DATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.CharField(default='MISSING WALLET', max_length=42),
        ),
    ]
