# Generated by Django 2.2.12 on 2021-02-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210202_0653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
